import { Data } from "@angular/router"

export interface PhysicalAssessment {
  physicalAssessmentId?: number,
  userId?: number,
  userName?: string,
  userEmail?: string,
  physicalAssessmentDate?: Date,
  professionalId?: number,
  height?: number,
  generalDescription?: number,
  idealWeight?: number,
  actualWeight?: number,
  relaxedRightArm?: number,
  relaxedLeftArm?: number,
  contractedRightArm?: number,
  contractedLeftArm?: number,
  rightForearm?: number,
  leftForearm?: number,
  rightFist?: number,
  leftFist?: number,
  neck?: number,
  chest?: number,
  abdomen?: number,
  shoulder?: number,
  waist?: number,
  hip?: number,
  rightCalf?: number,
  leftCalf?: number,
  rightThigh?: number,
  leftThigh?: number,
  rightProximalThigh?: number,
  leftProximalThigh?: number,
  boneFistDiameter?: number,
  femur?: number,
  skinFoldsBiceps?: number,
  skinFoldsTriceps?: number,
  skinFoldsAbdominal?: number,
  skinFoldsSuprailiac?: number,
  skinFoldsMediumArmpit?: number,
  skinFoldsChest?: number,
  skinFoldsSubscapularis?: number,
  skinFoldsThigh?: number,
  skinMedialCalf?: number,
  imc?: number,
  fatMass?: number,
  corporalWater?: number,
  residualWeight?: number,
  visceralFat?: number,
  leanMass?: number,
  muscularWeight?: number,
  metabolicAge?: number,
  boneWeight?: number,
  description?: string,
  filePath?: string
}

export type PhysicalAssessments = Array<PhysicalAssessment>
