import { Data } from "@angular/router"

export interface PhysicalAssessment {
  physical_assessment_id?: number,
  userId ?: number,
  userName ?: string,
  userEmail ?: string,
  physical_assessment_date?: Date,
  professionalId?: number,
  height?: number,
  general_description?: number,
  ideal_weight?: number,
  actual_weight?: number,
  relaxed_right_arm?: number,
  relaxed_left_arm?: number,
  contracted_right_arm?: number,
  contracted_left_arm?: number,
  right_forearm?: number,
  left_forearm?: number,
  right_fist?: number,
  left_fist?: number,
  neck?: number,
  chest?: number,
  abdomen?: number,
  shoulder?: number,
  waist?: number,
  hip?: number,
  right_calf?: number,
  left_calf?: number,
  right_thigh?: number,
  left_thigh?: number,
  right_proximal_thigh?: number,
  left_proximal_thigh?: number,
  bone_fist_diameter?: number,
  femur?: number,
  skin_folds_biceps?: number,
  skin_folds_triceps?: number,
  skin_folds_abdominal?: number,
  skin_folds_suprailiac?: number,
  skin_folds_medium_armpit?: number,
  skin_folds_chest?: number,
  skin_folds_subscapularis?: number,
  skin_folds_thigh?: number,
  skin_medial_calf?: number,
  IMC?: number,
  fat_mass?: number,
  corporal_water?: number,
  residual_weight?: number,
  visceral_fat?: number,
  lean_mass?: number,
  muscular_weight?: number,
  metabolic_age?: number,
  bone_weight?: number,
  description ?: string,
}

export type PhysicalAssessments = Array<PhysicalAssessment>
