INSERT INTO roles(name, created_at, deleted_at) VALUES
    ('ADMIN', now(), null),
    ('PROFESSOR', now(), null),
    ('ALUNO', now(), null),
    ('NUTRICIONISTA', now(), null);

INSERT INTO states(state, uf) VALUES
   ('Rondônia','RO'),
   ('Acre','AC'),
   ('Amazonas','AM'),
   ('Roraima','RR'),
   ('Pará','PA'),
   ('Amapá','AP'),
   ('Tocantins','TO'),
   ('Maranhão','MA'),
   ('Piauí','PI'),
   ('Ceará','CE'),
   ('Rio Grande do Norte','RN'),
   ('Paraíba', 'PB'),
   ('Pernambuco','PE'),
   ('Alagoas','AL'),
   ('Sergipe','SE'),
   ('Bahia','BA'),
   ('Minas Gerais','MG'),
   ('Espírito Santo','ES'),
   ('Rio de Janeiro','RJ'),
   ('São Paulo','SP'),
   ('Paraná','PR'),
   ('Santa Catarina','SC'),
   ('Rio Grande do Sul','RS'),
   ('Mato Grosso do Sul','MS'),
   ('Mato Grosso','MT'),
   ('Goiás','GO'),
   ('Distrito Federal','DF');
